### ISSUE TITLE
Perturbation forces crash with OpenSim4

### ISSUE THREAD

**Issue by afhidalgo** [tgeijten/scone-core#4]
**Describe the bug**
Perturbation forces
SCONE completely crash when I intend to introduce external forces. I enable the external force making “enable_external_forces = 1” but I think the problem is when using OpenSim4. When I used SCONE example provided in the Tutorials, the model works but, it is an OpenSim3 model

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - SCONE Version [2.0.0.2132 BETA 9] (I also had this problem with previous version as 1.5

**Comment by tgeijten** [comment]
Thanks -- I'm able to reproduce the crash. Unfortunately, the error occurs somewhere deep within the OpenSim code, so it's not immediately clear what's going on. I will need to spend more time on this.

**Comment by tgeijten** [comment]
Fixed
